type TokenIndex @entity(immutable: false) {
  id: String! # conditionId-tokenIndex
  conditionId: Bytes!
  tokenIndex: Int! # 0 for yes, 1 for no
  tokenId: BigInt!

  #Index fields
  twapIndex: BigInt! # sum(price(1e6) * seconds)
  startedAt: BigInt # timestamp
  lastUpdatedAt: BigInt # timestamp
  lastPrice: BigInt # 6 decimals
  #Resolved fields
  resolvedAt: BigInt
  resolvedPrice: BigInt # 6 decimals
  #Robin index fields
  robinLastUpdatedAt: BigInt
  robinTwapIndexYes: BigInt
  robinInitializedAt: BigInt
  twapIndexAtRobinInitializedAt: BigInt
  #Robin resolved fields
  robinResolvedAt: BigInt
  robinResolvedPrice: BigInt
}
